config/routes.rb
Rails.application.routes.draw do

  resources :items do
    resources :bookings
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  namespace :users do
    get 'dashboard'
  end

  get 'pages/index' => 'pages#index'

  root 'pages#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :item
  belongs_to :customer, class_name: "User"

  validates :item, presence: true
  validates :customer, presence: true
  validates :start_day, presence: true
  validates :end_day, presence: true

  def owner
    item.owner
  end

end

app/models/item.rb
  class Item < ActiveRecord::Base


  has_attached_file :picture,
    styles: { medium: "1000x1000>", thumb: "100x100>", card: "345x230>", add: "500x335>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  belongs_to :owner, class_name: "User"
  has_many :bookings, dependent: :destroy

  validates :category, presence: true
  validates :title, presence: true
  validates :owner, presence: :true
  validates :daily_price, presence: :true
  validates :brand, presence: :true
  validates :city, presence: :true
  validates :picture, presence: :true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :items, dependent: :destroy, foreign_key: "owner_id"
  has_many :item_bookings, through: :items, source: :bookings
  has_many :bookings, dependent: :destroy, foreign_key: "customer_id"

  after_create :send_welcome_email

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  end

  def show
    @item = Item.find(params[:item_id])
    @owner = User.find(@item.owner_id)
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @item = Item.find(params[:item_id])
    @owner = User.find(@item.owner_id)
    @booking = @item.bookings.new(params_bookings)
    @booking.start_day = DateTime.strptime(params[:booking][:start_day], '%m/%d/%Y').to_date
    @booking.end_day = DateTime.strptime(params[:booking][:end_day], '%m/%d/%Y').to_date
    @booking.item_id = @item.id
    @booking.customer = current_user
    @booking.status = "Waiting"
    if @booking.save
      redirect_to users_dashboard_path(:anchor => "travelers")
      flash[:notice] = "Your booking request of #{@booking.item.title} has been created :)"
      BookingMailer.booking_request_confirmation(@booking).deliver_now
      BookingMailer.new_booking_request(@booking).deliver_now
    else
      redirect_to :back
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @item = @booking.item
    @owner = @booking.owner
    @customer = @booking.customer
  end

  def update
    @booking = Booking.find(params[:id])
    @item = @booking.item
    @owner = @booking.owner
    @customer = @booking.customer
    if @booking.update(params_bookings_answer)
      if @booking.status == "Accept"
        redirect_to users_dashboard_path
      else
        redirect_to users_dashboard_path
      end
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
  def params_bookings
    params.require(:booking).permit(:start_day, :end_day)
  end

  def params_bookings_answer
    params.require(:booking).permit(:start_day, :end_day, :status)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :find_item, only: [:show, :destroy, :edit, :update]
  def index
    if params.has_key? "category"
        @items = Item.where(category: params["category"])
      if params.has_key? "max_price"
        @items = @items.where('daily_price < ?', params["max_price"])
      end
    else
      @items = Item.all
    end

  end

  def show
    @booking = Booking.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.owner_id = current_user.id if current_user
    if @item.save
      flash[:notice] = "#{@item.title} has been created"
      redirect_to item_path(@item)
      ItemMailer.add_confirmation(@item).deliver_now
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end


  def destroy
    @item = Item.destroy(find_item)
    flash[:notice] = "#{@item.title} has been deleted"
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :daily_price, :description, :category, :brand, :city, :picture)
  end
  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @items = Item.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      flash[:alert] = "We need your email, please contact us!"
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: :dashboard
  def dashboard
    @user = current_user
    @bookings = @user.bookings
    @item_bookings = @user.item_bookings
    @items = @user.items
    @sales = @user.item_bookings
    @owner = @user.bookings
    @customer = @user.item_bookings
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private
   def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<div class="booking-created">
  <h1>New booking request received</h1>
</div>
<h1 class="text-center" style="margin-bottom: 20px"> <%= @item.title %> </h1>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">

        <div class="col-xs-12 col-md-8" style="padding-right: 0px">
          <div class="show-pic">
            <%= image_tag @item.picture.url(:add), class:"img-show" %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4" style="padding-right: 10px padding-left: 10px">
          <div class="request-form">
            <h2 class="text-center" style="padding-bottom:20px">Request</h2>

            <ul>
              <li class="list-group-item">From: <%= @booking.start_day %></li>
              <li class="list-group-item">To: <%= @booking.end_day %></li>
              <li class="list-group-item">Total price: <%= (@item.daily_price * (@booking.end_day - @booking.start_day)).to_i %>€ </li>

              <li class="list-group-item">Email: <%= @owner.email %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <% if @owner == current_user %>
      <%= simple_form_for [@item, @booking] do |f| %>
        <ul class="list-inline text-center">
          <li>Answer:</li>
          <li><%= f.input :status, as: :select, collection: ["Accept", "Refuse"] %><li>
          <li><%= f.submit "Send", class:"btn btn-success" %></li>
        </ul>
      <% end %>
    <% else %>
      <%= simple_form_for [@item, @booking] do |f| %>
        <ul class="list-inline text-center">
          <li>Answer:</li>
          <li><%= f.input :status, as: :select, collection: ["Cancel", "Modify"] %><li>
          <li><%= f.submit "Send", class:"btn btn-success" %></li>
        </ul>
      <% end %>
    <% end %>


      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <ul class="list-group listing">
          <li class="list-group-item">Description : <%= @item.description %></li>
          <li class="list-group-item">Price : <%= @item.daily_price.round %>€ per day</li>
          <li class="list-group-item">Category : <%= @item.category %></li>
          <li class="list-group-item">Brand : <%= @item.brand %></li>
          <li class="list-group-item">Rented by : <%= @item.owner.first_name %> <%= @item.owner.last_name %></li>
          <li class="list-group-item">Available in : <%= @item.city %></li>
        </ul>
      </div>

    </div>

  </div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/show.html.erb
<div class="booking-created">
  <h1>Booking resquest sent with success</h1>
</div>
<h1 class="text-center" style="margin-bottom: 20px"> <%= @item.title %> </h1>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">

        <div class="col-xs-12 col-md-8" style="padding-right: 0px">
          <div class="show-pic">
            <%= image_tag @item.picture.url(:add), class:"img-show" %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4" style="padding-right: 10px padding-left: 10px">
          <div class="request-form">
            <h2 class="text-center" style="padding-bottom:20px">Request</h2>

            <ul>
              <li class="list-group-item">From: <%= @booking.start_day %></li>
              <li class="list-group-item">To: <%= @booking.end_day %></li>
              <li class="list-group-item">Total price: <%= (@item.daily_price * (@booking.end_day - @booking.start_day)).to_i %>€ </li>
              <li class="list-group-item">Contact: <%= @owner.email %></li>
            </ul>

          </div>
        </div>
      </div>

    </div>

      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <ul class="list-group listing">
          <li class="list-group-item">Description: <%= @item.description %></li>
          <li class="list-group-item">Price: <%= @item.daily_price.round %>€ per day</li>
          <li class="list-group-item">Category: <%= @item.category %></li>
          <li class="list-group-item">Brand: <%= @item.brand %></li>
          <li class="list-group-item">Rented by: <%= @item.owner.first_name %> <%= @item.owner.last_name %></li>
          <li class="list-group-item">Available in: <%= @item.city %></li>
        </ul>
      </div>

    </div>

  </div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Edit <%= @item.title %></h2>
      <%= simple_form_for(@item) do |f| %>
        <%= f.input :title, placeholder: "Oyster perpetual rolex" %>
        <%= f.input :daily_price, placeholder: "19" %>
        <%= f.input :description, as: :text %>
        <%= f.input :category, collection: [ "Watch", "Jewels", "Handbag"] %>
        <%= f.input :brand %>
        <%= f.input :city, as: :hidden, :input_html => { :value => "Paris" } %>
        <%= image_tag @item.picture.url(:medium) %>
        <%= f.input :picture %>
        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
      <% if @items.empty? %>
        <div class="text-center">
          <h2 class="text-center">Sorry no product found </h2>
          <button onclick="goBack()" class="btn btn-danger">Go Back</button>
        </div>
        <script>
          function goBack() {
              window.history.back();
          }
        </script>
      <% else %>
          <div class="col-xs-12 col-sm-4">
            <div class="search-form">
              <h2 class="text-center" style="padding-bottom:20px">Filters</h2>
                <ul class="list-unstyled">
                  <li>

                      <% if params.has_key? "category" %>

                        <input id="ex1" data-slider-id='ex1Slider' data-slider-min="10" data-slider-max="500" data-slider-step="1" data-slider-value="500"/><br /> <br />

                        <%= form_tag '/items', :method => :get do %>
                          <%= hidden_field_tag 'category', @items.first.category %>
                          Max price <%= number_field_tag 'max_price' %>
                          <%= submit_tag "Search", class: "btn btn-success" %>
                        <% end %>
                      <% else %>
                        <%= form_tag '/items', id: "category_choice", class: "form-inline", :method => :get do %>
                          <%= select_tag "category", options_for_select([ "Watch", "Jewel", "Handbag" ]),class: "form-control", prompt: "What do you want to rent ?" %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </ul>
                </div>
              </div>

          <div class="col-xs-12 col-sm-8">
            <% if @items.empty? %>
            <% else %>

              <% if params.has_key? "category" %>
              <h1 class="text-center"><%= @items.count %> <%= @items.count > 1 ? @items.first.category.pluralize : @items.first.category.singularize %> found </h1>


            <% end %>

                <% @items.each do |item| %>
                  <div class="col-xs-12 col-sm-6">
                    <%= render 'shared/card_result', item: item %>
                  </div>
                <% end %>
              <% end %>
        </div>
      </ul>
    </div>
  </div>
</div>
<% content_for(:js) do%>
  <%= javascript_tag do %>
  $('#ex1').slider({
    formatter: function(value) {
      $('#max_price').val(value);
    }
  });

<% end %>
<% end %>

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Post a new item</h2>
      <%= simple_form_for(@item) do |f| %>
        <%= f.input :title, placeholder: "Oyster perpetual rolex" %>
        <%= f.input :daily_price, placeholder: "19" %>
        <%= f.input :description, as: :text %>
        <%= f.input :category, collection: [ "Watch", "Jewel", "Handbag"] %>
        <%= f.input :brand %>
        <%= f.input :city, as: :hidden, :input_html => { :value => "Paris" } %>
        <%= f.input :picture %>
        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<h1 class="text-center" style="margin-bottom: 50px"> <%= @item.title %> </h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">

      <div class="col-xs-12 col-md-8" style="padding-right: 0px">
        <div class="show-pic">
          <%= image_tag @item.picture.url(:add), class:"img-show" %>
        </div>
      </div>

      <div class="col-xs-12 col-md-4 block-img">
        <div class="request-form">

          <% if @item.owner == current_user %>
            <h2>Manage your add</h2>
            <%= link_to "Edit this item", edit_item_path(@item), class: "btn btn-warning" %>
            <br><br>
            <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: 'Are you sure you want to delete this ?' }, class: "btn btn-danger" %>

          <% else %>

          <h2 class="text-center" style="padding-bottom:20px">Booking</h2>
          <%= simple_form_for [@item, @booking] do |f| %>
            <ul class="list-inline">
              <li><%= f.input :start_day, label: "From:", as: :string, input_html: { class:"datepicker" }, error: 'Starting day should be a good day' %><li>
              <li><%= f.input :end_day, label: "To:", as: :string, input_html: { class:"datepicker" }, error: 'Starting day should be a bad day' %><li>
            </ul>
            <div class="text-center">
            <%= f.submit "Send request", class:"btn btn-success" %>
            </div>
           <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>

    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <ul class="list-group listing">
        <li class="list-group-item">Description : <%= @item.description %></li>
        <li class="list-group-item">Price : <%= @item.daily_price.round %>€ per day</li>
        <li class="list-group-item">Category : <%= @item.category %></li>
        <li class="list-group-item">Brand : <%= @item.brand %></li>
        <li class="list-group-item">Rented by : <%= @item.owner.first_name %> <%= @item.owner.last_name %></li>
        <li class="list-group-item">Available in : <%= @item.city %></li>
      </ul>
    </div>

  </div>

</div>

<div class="text-center">
  <%= link_to "Back to items list", items_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luxury Access - The luxury way to rent luxury items</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body class="<%= controller_name %>-<%= action_name %>">

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= render 'shared/footer' %>
    <%= yield(:js) %>
  </body>
</html>

app/views/pages/index.html.erb
<header class="montruc">
  <div class="content">
    <hgroup>
      <h1>Access luxury for a day</h1>
      <h2>Rent jewelry, watches and bags from the best designers</h2>
        <% if params.has_key? "category" %>
          <%= form_tag '/items', class: "form-inline", :method => :get do %>
            <%= hidden_field_tag 'category', @items.first.category %>
            <%= number_field_tag 'max_price' %>
            <%= submit_tag "Search", class: "btn btn-success" %>
          <% end %>
        <% else %>
           <%= form_tag '/items', id: "category_choice", class: "form-inline", :method => :get do %>
              <%= select_tag "category", options_for_select([ "Watch", "Jewel", "Handbag" ]),class: "form-control", prompt: "What do you want to rent ?" %>
            <% end %>
         <% end %>
    </hgroup>
  </div>
</header>

app/views/shared/_card_dashboard.html.erb
<div class="container ">
  <div class="row">
    <div class="col-xs-12">

      <div class="col-xs-12 col-sm-6" style="padding-right: 0px">
        <div class="img-dash vignette">
          <span class="card-bg" style="background-image: url('<%= image_path booking.item.picture.url(:card) %>')"></span>
          <%= link_to item_booking_path(booking.item, booking), {class:"card-link"} do %>
          <% end %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-3 vignette" style="padding-right: 10px padding-left: 10px">
        <ul class="list-group listing vignette">
          <li class="list-group-item"><%= booking.item.title %></li>
          <li class="list-group-item">From: <%= booking.start_day %></li>
          <li class="list-group-item">Category: <%= booking.item.category %></li>
          <li class="list-group-item">Price: <%= booking.item.daily_price.round %>€ per day</li>
          <li class="list-group-item">Rented by: <%= booking.item.owner.first_name %> <%= booking.item.owner.last_name %></li>
        </ul>
      </div>

      <div class="col-xs-12 col-sm-3 vignette">
        <ul class="list-group listing vignette">
          <li class="list-group-item">Available in: <%= booking.item.city %></li>
          <li class="list-group-item">To: <%= booking.end_day %></li>
          <li class="list-group-item">Brand: <%= booking.item.brand %></li>
          <li class="list-group-item">Total price: <%= (booking.item.daily_price * (booking.end_day - booking.start_day)).to_i %>€ </li>
          <li class="list-group-item"><%= booking.item.owner.email %></li>
        </ul>
      </div>

          <div class="col-xs-12 text-center change-status">
            <% if booking.owner == current_user %>
              <%= simple_form_for [booking.item, booking] do |f| %>
                <ul class="list-inline text-center">
                  <li>Statut:</li>
                  <li><%= f.input :status, label:false, as: :select, collection: ["Accept", "Refuse"] %></li>
                  <li><%= f.submit "Change", class:"btn btn-success" %></li>
                </ul>
              <% end %>
            <% else %>
              <%= simple_form_for [booking.item, booking] do |f| %>
                <ul class="list-inline text-center">
                  <li>Statut:</li>
                  <li><%= f.input :status, label:false, as: :select, collection: ["Cancel"] %><li>
                  <li><%= f.submit "Change", class:"btn btn-success" %></li>
                </ul>
              <% end %>
            <% end %>
          </div>

    </div>
  </div>
  <hr>
</div>

app/views/shared/_card_result.html.erb
<div class="card">
  <span class="card-bg" style="background-image: url('<%= image_path item.picture.url(:card) %>')"></span>
  <span class="card-gradient"></span>
  <span class="card-category"><%= item.brand %></span>
  <span class="card-text">
    <h2><%= item.title %></h2>
    <p><%= item.daily_price %> €/j</p>
  </span>
  <span class="card-user">
    <%= image_tag item.owner.picture, class: "avatar avatar-bordered" %>
  </span>
  <%= link_to item_path(item), {class:"card-link"} do %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-horizontal">
  <footer>
    <div class="copyright">
      <p><strong>Luxury Access</strong> - The luxury way to rent luxury items</p>
    </div>
    <div class="social">
      <a href="#" class="support">Contact Us</a>
      <a href="#" class="face">f</a>
      <a href="#" class="tweet">t</a>
      <a href="#" class="linked">in</a>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">

     <%= image_tag "logo.png", class: "navbar-wagon-logo" %> <font face="$logo-font">Luxury Access</font>


   </a>

    <div class="navbar-wagon-pusher"></div>

    <form action="" class="navbar-wagon-search hidden-xs hidden-sm">
    <!--   <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn"> -->
<!--         <i class="fa fa-search"></i> -->
<!--       </button> -->
    </form>
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to users_dashboard_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Dashboard" %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <hr>
    <%= link_to t(".top_call_to_action", default: "Post an add"), new_item_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <hr>
      <%= link_to t(".top_call_to_action", default: "Sign up now !"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/dashboard.html.erb
<h1 class="text-center">Dashboard</h1>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#offer" aria-controls="offer" role="tab" data-toggle="tab">My Items</a></li>
    <li role="presentation"><a href="#travelers" aria-controls="travelers" role="tab" data-toggle="tab">Requests sent</a></li>
    <li role="presentation"><a href="#bookings" aria-controls="bookings" role="tab" data-toggle="tab">Requests received</a></li>
    <li role="presentation"><a href="#edit" aria-controls="edit" role="tab" data-toggle="tab">Edit profile</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="offer">
      <div class="container">
        <div class="row">
          <h2 class="dashboard-title"><%= @items.count %> <%= @items.count > 1 ? "Offers online" : "Offer online" %></h2>
          <% @items.each do |item| %>
            <div class="col-xs-12 col-sm-6">
              <%= render 'shared/card_result', item: item %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Mes achats -->
    <div role="tabpanel" class="tab-pane" id="travelers">
      <h2 class="dashboard-title"><%= @items.count > 1 ? "Booking requests I have made" : "Booking request I have made" %></h2>
      <% @bookings.each do |booking| %>
        <%= render 'shared/card_dashboard', booking: booking %>


    <% end %>
    </div>

    <!-- Mes ventes -->
    <div role="tabpanel" class="tab-pane" id="bookings">
      <h2 class="dashboard-title"><%= @items.count > 1 ? "Booking requests I have received" : "Booking request I have received" %></h2>
      <% @sales.each do |sale| %>
        <%= render 'shared/card_dashboard', booking: sale %>
      <% end %>

    </div>

    <div role="tabpanel" class="tab-pane" id="edit">
    <h2 class="dashboard-title">Edit my profile</h2>
     <%= render "devise/registrations/edit", resource_name: :user, resource: current_user, devise_mapping: nil %>
   </div>
  </div>

</div>
  </div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>